# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=redactor.fields.RedactorField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
