# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
