# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='test', max_length=50, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=70, verbose_name='\u0413\u0430\u0440\u0447\u0438\u0433'),
        ),
    ]
