# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20170328_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='face', max_length=50, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
