# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(max_length=50, null=True, verbose_name='Google'),
        ),
    ]
