# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_profile_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='\u041c\u0438\u043d\u0438\u0439 \u0442\u0443\u0445\u0430\u0439'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041c\u044d\u0440\u0433\u044d\u0436\u0438\u043b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u043e\u0432\u0435\u0440 \u0437\u0443\u0440\u0430\u0433'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041f\u0440\u043e\u0444\u0430\u0439\u043b \u0437\u0443\u0440\u0430\u0433'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter'),
        ),
    ]
